export enum Fonts {
  PlayfairDisplay = 'PlayfairDisplay-Regular',
  PlayfairDisplay_Medium = 'PlayfairDisplay-Medium',
  PlayfairDisplay_Bold = 'PlayfairDisplay-Bold',
  PlayfairDisplay_ExtraBold = 'PlayfairDisplay-ExtraBold',
  RobotoSlab_Black = 'RobotoSlab-Black',
  RobotoSlab_Bold = 'RobotoSlab-Bold',
  RobotoSlab_ExtraBold = 'RobotoSlab-ExtraBold',
  RobotoSlab_ExtraLight = 'RobotoSlab-ExtraLight',
  RobotoSlab_Light = 'RobotoSlab-Light',
  RobotoSlab_Medium = 'RobotoSlab-Medium',
  RobotoSlab = 'RobotoSlab-Regular',
  RobotoSlab_SemiBold = 'RobotoSlab-SemiBold',
  RobotoSlab_Thin = 'RobotoSlab-Thin',
}
